# Generated by Django 6.0.6 on 2026-06-30 10:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('reference_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('abstract', models.TextField()),
                ('methodology', models.TextField()),
                ('expected_outcomes', models.TextField(blank=True)),
                ('budget_requested', models.DecimalField(decimal_places=2, max_digits=15)),
                ('duration_months', models.PositiveIntegerField()),
                ('team_members', models.TextField(blank=True, help_text='JSON structured list of team members and roles')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested')], db_index=True, default='DRAFT', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('revision_comments', models.TextField(blank=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='grants.grant')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
                'ordering': ['-created_at'],
                'unique_together': {('grant', 'submitted_by')},
            },
        ),
        migrations.CreateModel(
            name='ProposalAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='proposal_attachments/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='proposals.proposal')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proposal Attachment',
                'verbose_name_plural': 'Proposal Attachments',
            },
        ),
        migrations.CreateModel(
            name='ProposalReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('methodology_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('impact_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('feasibility_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('budget_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('comments', models.TextField()),
                ('recommendation', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REVISE', 'Request Revision')], max_length=20)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='proposals.proposal')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposal_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proposal Review',
                'verbose_name_plural': 'Proposal Reviews',
                'ordering': ['-reviewed_at'],
                'unique_together': {('proposal', 'reviewer')},
            },
        ),
    ]
