# Generated by Django 6.0.6 on 2026-07-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalattachment',
            name='document_type',
            field=models.CharField(choices=[('CV', 'CV / Resume'), ('BUDGET_PLAN', 'Budget Plan'), ('RESEARCH_PLAN', 'Research Plan'), ('ETHICS_APPROVAL', 'Ethics Approval'), ('LETTER_OF_SUPPORT', 'Letter of Support'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
