# Generated by Django 6.0.6 on 2026-07-07 08:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_proposalattachment_document_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalAIReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField()),
                ('risk_score', models.PositiveIntegerField(default=0, help_text='0 = low risk, 100 = high risk', validators=[django.core.validators.MaxValueValidator(100)])),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('suggested_recommendation', models.CharField(blank=True, max_length=20)),
                ('raw_response', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_ai_reviews', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_review', to='proposals.proposal')),
            ],
            options={
                'verbose_name': 'Proposal AI Review',
                'verbose_name_plural': 'Proposal AI Reviews',
            },
        ),
    ]
