# Generated by Django 6.0.6 on 2026-07-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_proposalaireview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together=set(),
        ),
    ]
