# Generated by Django 6.0.6 on 2026-07-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='title',
            field=models.CharField(blank=True, help_text='Optional custom name for this budget, distinct from the grant title.', max_length=255),
        ),
    ]
