# Generated by Django 6.0.6 on 2026-07-07 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budget_title'),
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='grants.grant'),
        ),
    ]
