# Generated by Django 6.0.6 on 2026-06-30 10:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('PROPOSAL_SUBMITTED', 'Proposal Submitted'), ('PROPOSAL_APPROVED', 'Proposal Approved'), ('PROPOSAL_REJECTED', 'Proposal Rejected'), ('PROPOSAL_REVISION', 'Revision Requested'), ('GRANT_OPENED', 'Grant Opportunity Opened'), ('GRANT_AWARDED', 'Grant Awarded'), ('GRANT_COMPLETED', 'Grant Completed'), ('REVIEW_ASSIGNED', 'Review Assigned'), ('REVIEW_COMPLETED', 'Review Completed'), ('MILESTONE_DUE', 'Milestone Due Soon'), ('MILESTONE_OVERDUE', 'Milestone Overdue'), ('DISBURSEMENT_APPROVED', 'Disbursement Approved'), ('DISBURSEMENT_REJECTED', 'Disbursement Rejected'), ('REPORT_SUBMITTED', 'Report Submitted'), ('REPORT_REVIEWED', 'Report Reviewed'), ('SYSTEM', 'System Alert')], db_index=True, default='SYSTEM', max_length=30)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('link', models.CharField(blank=True, help_text='Front-end URL path to navigate to when clicked', max_length=500)),
                ('related_object_type', models.CharField(blank=True, help_text='Model name of the related entity', max_length=50)),
                ('related_object_id', models.CharField(blank=True, help_text='Primary key of the related entity', max_length=50)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
